# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMovieDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMovieDB
    pod 'Alamofire'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'MBProgressHUD'
    pod 'Kingfisher', '~> 5.14'
    pod 'SwiftMessages'

  target 'TheMovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
